
package vista;
import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.awt.Desktop;

public class Calculadora extends javax.swing.JFrame {

    public float primernumero =0
                ,segundonumero=0;
    public String operador ="";

    public Calculadora() {
        initComponents();
        //hacer aparecer el formulario al centro de la pantalla   
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_casilla = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_restar = new javax.swing.JButton();
        btn_num7 = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_num9 = new javax.swing.JButton();
        btn_num4 = new javax.swing.JButton();
        btn_num5 = new javax.swing.JButton();
        btn_num6 = new javax.swing.JButton();
        btn_num1 = new javax.swing.JButton();
        btn_num2 = new javax.swing.JButton();
        btn_num3 = new javax.swing.JButton();
        btn_num0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_num8 = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_sumar = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        jmb_menuprincipal = new javax.swing.JMenuBar();
        jm_opciones = new javax.swing.JMenu();
        jmi_nuevo = new javax.swing.JMenuItem();
        jmi_historial = new javax.swing.JMenuItem();
        jm_ayuda = new javax.swing.JMenu();
        jmi_manual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lbl_casilla.setBackground(new java.awt.Color(204, 255, 204));
        lbl_casilla.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_casilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_casilla.setOpaque(true);

        btn_salir.setBackground(new java.awt.Color(255, 255, 153));
        btn_salir.setFont(new java.awt.Font("Spinnaker", 0, 10)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setBorder(null);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_restar.setBackground(new java.awt.Color(153, 204, 255));
        btn_restar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_restar.setText("-");
        btn_restar.setBorder(null);
        btn_restar.setOpaque(true);
        btn_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarActionPerformed(evt);
            }
        });

        btn_num7.setBackground(new java.awt.Color(102, 102, 102));
        btn_num7.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num7.setForeground(new java.awt.Color(255, 255, 255));
        btn_num7.setText("7");
        btn_num7.setBorder(null);
        btn_num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num7ActionPerformed(evt);
            }
        });

        btn_dividir.setBackground(new java.awt.Color(153, 204, 255));
        btn_dividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_dividir.setText("/");
        btn_dividir.setBorder(null);
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });

        btn_num9.setBackground(new java.awt.Color(102, 102, 102));
        btn_num9.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num9.setForeground(new java.awt.Color(255, 255, 255));
        btn_num9.setText("9");
        btn_num9.setBorder(null);
        btn_num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num9ActionPerformed(evt);
            }
        });

        btn_num4.setBackground(new java.awt.Color(102, 102, 102));
        btn_num4.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num4.setForeground(new java.awt.Color(255, 255, 255));
        btn_num4.setText("4");
        btn_num4.setBorder(null);
        btn_num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num4ActionPerformed(evt);
            }
        });

        btn_num5.setBackground(new java.awt.Color(102, 102, 102));
        btn_num5.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num5.setForeground(new java.awt.Color(255, 255, 255));
        btn_num5.setText("5");
        btn_num5.setBorder(null);
        btn_num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num5ActionPerformed(evt);
            }
        });

        btn_num6.setBackground(new java.awt.Color(102, 102, 102));
        btn_num6.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num6.setForeground(new java.awt.Color(255, 255, 255));
        btn_num6.setText("6");
        btn_num6.setBorder(null);
        btn_num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num6ActionPerformed(evt);
            }
        });

        btn_num1.setBackground(new java.awt.Color(102, 102, 102));
        btn_num1.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num1.setForeground(new java.awt.Color(255, 255, 255));
        btn_num1.setText("1");
        btn_num1.setBorder(null);
        btn_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num1ActionPerformed(evt);
            }
        });

        btn_num2.setBackground(new java.awt.Color(102, 102, 102));
        btn_num2.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num2.setForeground(new java.awt.Color(255, 255, 255));
        btn_num2.setText("2");
        btn_num2.setBorder(null);
        btn_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num2ActionPerformed(evt);
            }
        });

        btn_num3.setBackground(new java.awt.Color(102, 102, 102));
        btn_num3.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num3.setForeground(new java.awt.Color(255, 255, 255));
        btn_num3.setText("3");
        btn_num3.setBorder(null);
        btn_num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num3ActionPerformed(evt);
            }
        });

        btn_num0.setBackground(new java.awt.Color(102, 102, 102));
        btn_num0.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num0.setForeground(new java.awt.Color(255, 255, 255));
        btn_num0.setText("0");
        btn_num0.setBorder(null);
        btn_num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num0ActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(102, 102, 102));
        btn_punto.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(255, 255, 255));
        btn_punto.setText(".");
        btn_punto.setBorder(null);
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_num8.setBackground(new java.awt.Color(102, 102, 102));
        btn_num8.setFont(new java.awt.Font("Spinnaker", 0, 18)); // NOI18N
        btn_num8.setForeground(new java.awt.Color(255, 255, 255));
        btn_num8.setText("8");
        btn_num8.setBorder(null);
        btn_num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_num8ActionPerformed(evt);
            }
        });

        btn_multiplicar.setBackground(new java.awt.Color(153, 204, 255));
        btn_multiplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_multiplicar.setText("*");
        btn_multiplicar.setBorder(null);
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        btn_sumar.setBackground(new java.awt.Color(153, 204, 255));
        btn_sumar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sumar.setText("+");
        btn_sumar.setBorder(null);
        btn_sumar.setOpaque(true);
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(255, 102, 102));
        btn_igual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_igual.setText("=");
        btn_igual.setBorder(null);
        btn_igual.setOpaque(true);
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_casilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_num4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_num5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_num6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_num7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(btn_num8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_num9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_restar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_num3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_num0, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_casilla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_restar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_num9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_num7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_num8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_num5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_num6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_num4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_sumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_num2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_num3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_punto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_num0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jmb_menuprincipal.setBackground(new java.awt.Color(153, 153, 153));
        jmb_menuprincipal.setBorder(null);
        jmb_menuprincipal.setOpaque(true);

        jm_opciones.setText("Opciones");

        jmi_nuevo.setText("Nuevo");
        jmi_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nuevoActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_nuevo);

        jmi_historial.setText("Historial");
        jmi_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_historialActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_historial);

        jmb_menuprincipal.add(jm_opciones);

        jm_ayuda.setText("Ayuda (?)");

        jmi_manual.setText("Manual de usuario");
        jmi_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_manualActionPerformed(evt);
            }
        });
        jm_ayuda.add(jmi_manual);

        jmb_menuprincipal.add(jm_ayuda);

        setJMenuBar(jmb_menuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // Método para reproducir sonido
    private void playSound(String soundFile) {
        try {
            File file = new File(soundFile);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(file);
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            ex.printStackTrace();
        }
    }
    
// Método para crear el archivo si no existe
private void crearArchivo() {
    File archivo = new File("BitacoraCalculadora.txt");
    try {
        if (archivo.createNewFile()) {
            System.out.println("Archivo creado: " + archivo.getName());
        } else {
            System.out.println("El archivo ya existe.");
        }
    } catch (IOException e) {
        System.out.println("Ocurrió un error al crear el archivo.");
        e.printStackTrace();
    }
}
    
// Método para escribir en el archivo
private void escribirEnArchivo(String texto) {
    try (FileWriter fw = new FileWriter("BitacoraCalculadora.txt", true);
         PrintWriter pw = new PrintWriter(fw)) {
        pw.println(texto);
    } catch (IOException e) {
        e.printStackTrace();
    }
}
// Método para abrir el archivo de texto
private void abrirHistorial() {
    // Ruta del archivo de texto
    File archivo = new File("BitacoraCalculadora.txt");
    
    // Verifica si el archivo existe
    if (archivo.exists()) {
        try {
            Desktop.getDesktop().open(archivo);
        } catch (IOException e) {
            System.out.println("Ocurrió un error al intentar abrir el archivo.");
            e.printStackTrace();
        }
    } else {
        System.out.println("El archivo no existe.");
    }
}
private void abrirManual() {
    // Ruta del archivo de texto
    File archivo = new File("MANUAL DE USUARIO.txt");
    
    // Verifica si el archivo existe
    if (archivo.exists()) {
        try {
            Desktop.getDesktop().open(archivo);
        } catch (IOException e) {
            System.out.println("Ocurrió un error al intentar abrir el archivo.");
            e.printStackTrace();
        }
    } else {
        System.out.println("El archivo no existe.");
    }
}

    private void btn_num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num0ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"0");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num0ActionPerformed

    private void btn_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num1ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"1");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num1ActionPerformed

    private void btn_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num2ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"2");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num2ActionPerformed

    private void btn_num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num3ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"3");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num3ActionPerformed

    private void btn_num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num4ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"4");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num4ActionPerformed

    private void btn_num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num5ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"5");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num5ActionPerformed

    private void btn_num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num6ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"6");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num6ActionPerformed

    private void btn_num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num7ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"7");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num7ActionPerformed

    private void btn_num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num8ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"8");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num8ActionPerformed

    private void btn_num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_num9ActionPerformed
        this.lbl_casilla.setText(this.lbl_casilla.getText()+"9");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_num9ActionPerformed

    private void jmi_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nuevoActionPerformed
        this.lbl_casilla.setText("");
        escribirEnArchivo("Nuevo");
    }//GEN-LAST:event_jmi_nuevoActionPerformed

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        this.primernumero=Float.parseFloat(this.lbl_casilla.getText());
        this.operador="+";
        this.lbl_casilla.setText("");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_sumarActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
       this.segundonumero=Float.parseFloat(this.lbl_casilla.getText());
       
       switch(this.operador){
            case "+" -> {this.lbl_casilla.setText(this.sincero(this.primernumero+this.segundonumero));
                            escribirEnArchivo(this.primernumero + " " + this.operador + " " + this.segundonumero + " = " + this.lbl_casilla.getText());}
            case "-" -> {this.lbl_casilla.setText(this.sincero(this.primernumero-this.segundonumero));
                            escribirEnArchivo(this.primernumero + " " + this.operador + " " + this.segundonumero + " = " + this.lbl_casilla.getText());}
            case "*" -> {this.lbl_casilla.setText(this.sincero(this.primernumero*this.segundonumero));
                            escribirEnArchivo(this.primernumero + " " + this.operador + " " + this.segundonumero + " = " + this.lbl_casilla.getText());}
            case "/" -> {
                        if (this.segundonumero==0) {
                        this.lbl_casilla.setText("ERROR");
                        escribirEnArchivo(this.primernumero + " " + this.operador + " " + this.segundonumero + " = " + this.lbl_casilla.getText());
                        } else {
                        this.lbl_casilla.setText(this.sincero(this.primernumero/this.segundonumero));
                        escribirEnArchivo(this.primernumero + " " + this.operador + " " + this.segundonumero + " = " + this.lbl_casilla.getText());
                        }
                    }
       }
       playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarActionPerformed
        this.primernumero=Float.parseFloat(this.lbl_casilla.getText());
        this.operador="-";
        this.lbl_casilla.setText("");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_restarActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        this.primernumero=Float.parseFloat(this.lbl_casilla.getText());
        this.operador="*";
        this.lbl_casilla.setText("");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
        this.primernumero=Float.parseFloat(this.lbl_casilla.getText());
        this.operador="/";
        this.lbl_casilla.setText("");
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_dividirActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        if(!(this.lbl_casilla.getText().contains("."))){
            this.lbl_casilla.setText(this.lbl_casilla.getText()+".");   
        }
        playSound("short-beep-tone-47916.wav");
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void jmi_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_historialActionPerformed
        abrirHistorial();
    }//GEN-LAST:event_jmi_historialActionPerformed

    private void jmi_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_manualActionPerformed
        abrirManual();
    }//GEN-LAST:event_jmi_manualActionPerformed

    public String sincero(float resultado){
        String retorno="";
        
        retorno=Float.toString(resultado);
        
        if(resultado%1==0){
            retorno=retorno.substring(0, retorno.length()-2);
        }
        
        return retorno;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_num0;
    private javax.swing.JButton btn_num1;
    private javax.swing.JButton btn_num2;
    private javax.swing.JButton btn_num3;
    private javax.swing.JButton btn_num4;
    private javax.swing.JButton btn_num5;
    private javax.swing.JButton btn_num6;
    private javax.swing.JButton btn_num7;
    private javax.swing.JButton btn_num8;
    private javax.swing.JButton btn_num9;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_restar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jm_ayuda;
    private javax.swing.JMenu jm_opciones;
    private javax.swing.JMenuBar jmb_menuprincipal;
    private javax.swing.JMenuItem jmi_historial;
    private javax.swing.JMenuItem jmi_manual;
    private javax.swing.JMenuItem jmi_nuevo;
    private javax.swing.JLabel lbl_casilla;
    // End of variables declaration//GEN-END:variables
}
